"""create conversation tables

Revision ID: 8870169332ea
Revises: 
Create Date: 2026-04-08 19:02:45.121821
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8870169332ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('parent_id', sa.String(length=64), nullable=False),
    sa.Column('parent_phone', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False, comment='Conversation source such as api, voice_call, or whatsapp'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Conversation lifecycle status such as active, paused, completed, or failed'),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_parent_id'), 'conversations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_conversations_parent_phone'), 'conversations', ['parent_phone'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='ID of the conversation this message belongs to'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Message role such as user, agent, or system'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=False, comment='1-based message order within a conversation'),
    sa.Column('resolved_student_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'message_index', name='uq_conversation_messages_conversation_id_message_index')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_messages_conversation_id_message_index', 'conversation_messages', ['conversation_id', 'message_index'], unique=False)
    op.create_index(op.f('ix_conversation_messages_resolved_student_id'), 'conversation_messages', ['resolved_student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_resolved_student_id'), table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conversation_id_message_index', table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversations_parent_phone'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_parent_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
