ENV_DEVELOPMENT = "development"
ENV_PRODUCTION = "production"

# Conversation channel describes where the parent is interacting from.
CHANNEL_API = "api"
CHANNEL_VOICE_CALL = "voice_call"
CHANNEL_WHATSAPP = "whatsapp"
CONVERSATION_CHANNELS = (
    CHANNEL_API,
    CHANNEL_VOICE_CALL,
    CHANNEL_WHATSAPP,
)

CONVERSATION_STATUS_ACTIVE = "active"
CONVERSATION_STATUS_PAUSED = "paused"
CONVERSATION_STATUS_COMPLETED = "completed"
CONVERSATION_STATUS_FAILED = "failed"
CONVERSATION_STATUSES = (
    CONVERSATION_STATUS_ACTIVE,
    CONVERSATION_STATUS_PAUSED,
    CONVERSATION_STATUS_COMPLETED,
    CONVERSATION_STATUS_FAILED,
)

MESSAGE_ROLE_USER = "user"
MESSAGE_ROLE_AGENT = "agent"
MESSAGE_ROLE_SYSTEM = "system"
MESSAGE_ROLES = (
    MESSAGE_ROLE_USER,
    MESSAGE_ROLE_AGENT,
    MESSAGE_ROLE_SYSTEM,
)

LLM_PROVIDER_OPENAI = "openai"
LLM_PROVIDER_ANTHROPIC = "anthropic"
LLM_PROVIDER_GEMINI = "gemini"
LLM_PROVIDERS = (
    LLM_PROVIDER_OPENAI,
    LLM_PROVIDER_ANTHROPIC,
    LLM_PROVIDER_GEMINI,
)

FEATURE_GENERATE_PARENT_QUERY_RESPONSE = "generate_parent_query_response"
FEATURE_REFRESH_CONVERSATION_SUMMARY = "refresh_conversation_summary"
MODEL_FEATURES = (
    FEATURE_GENERATE_PARENT_QUERY_RESPONSE,
    FEATURE_REFRESH_CONVERSATION_SUMMARY,
)

CONVERSATION_MESSAGE_TYPE_GREETING = "greeting"
CONVERSATION_MESSAGE_TYPE_PARENT_QUERY = "parent_query"
CONVERSATION_MESSAGE_TYPE_AGENT_ANSWER = "agent_answer"
CONVERSATION_MESSAGE_TYPE_AGENT_CLARIFICATION = "agent_clarification"
CONVERSATION_MESSAGE_TYPES = (
    CONVERSATION_MESSAGE_TYPE_GREETING,
    CONVERSATION_MESSAGE_TYPE_PARENT_QUERY,
    CONVERSATION_MESSAGE_TYPE_AGENT_ANSWER,
    CONVERSATION_MESSAGE_TYPE_AGENT_CLARIFICATION,
)

STUDENT_RESOLUTION_METHOD_EXACT_NAME_MATCH = "exact_name_match"
STUDENT_RESOLUTION_METHOD_AMBIGUOUS_NAME_MATCH = "ambiguous_name_match"
STUDENT_RESOLUTION_METHOD_FAMILY_RELATION_MATCH = "family_relation_match"
STUDENT_RESOLUTION_METHOD_AMBIGUOUS_RELATION_MATCH = "ambiguous_relation_match"
STUDENT_RESOLUTION_METHOD_PREVIOUS_RESOLVED_STUDENT_CONTEXT = (
    "previous_resolved_student_context"
)
STUDENT_RESOLUTION_METHOD_CLARIFICATION_REQUIRED = "clarification_required"
STUDENT_RESOLUTION_METHODS = (
    STUDENT_RESOLUTION_METHOD_EXACT_NAME_MATCH,
    STUDENT_RESOLUTION_METHOD_AMBIGUOUS_NAME_MATCH,
    STUDENT_RESOLUTION_METHOD_FAMILY_RELATION_MATCH,
    STUDENT_RESOLUTION_METHOD_AMBIGUOUS_RELATION_MATCH,
    STUDENT_RESOLUTION_METHOD_PREVIOUS_RESOLVED_STUDENT_CONTEXT,
    STUDENT_RESOLUTION_METHOD_CLARIFICATION_REQUIRED,
)
